#!/bin/sh

# This script wraps docker-php-ext-install, properly configuring the system.
# Let's set a sane environment
set -o errexit
set -o nounset
if test "${IPE_DEBUG:-}" = "1"; then
	set -x
fi

if ! which docker-php-ext-configure >/dev/null || ! which docker-php-ext-enable >/dev/null || ! which docker-php-ext-install >/dev/null || ! which docker-php-source >/dev/null; then
	printf 'The script %s is meant to be used with official Docker PHP Images - https://hub.docker.com/_/php\n' "$0" >&2
	exit 1
fi

IPE_VERSION=master

StandWithUkraine() {
	if test -t 1 && ! grep -Eq '^VERSION=.*jessie' /etc/os-release; then
		printf '\e[37;44m#StandWith\e[30;43mUkraine\e[0m\n'
	else
