#!/bin/sh

# This script wraps docker-php-ext-install, properly configuring the system.
# Let's set a sane environment
set -o errexit
set -o nounset
if test "${IPE_DEBUG:-}" = "1"; then
	set -x
fi

if ! which docker-php-ext-configure >/dev/null || ! which docker-php-ext-enable >/dev/null || ! which docker-php-ext-install >/dev/null || ! which docker-php-source >/dev/null; then
	printf 'The script %s is meant to be used with official Docker PHP Images - https://hub.docker.com/_/php\n' "$0" >&2
	exit 1
